persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_timestamp true
connection_messages true

listener 1883
protocol mqtt
listener_allow_anonymous false
password_file /mosquitto/data/password.txt
